### ISSUE TITLE
Copy generated struct to clipboard

### ISSUE THREAD

**Issue by Vhndaree** [samit22/json-go#1]
Instead of only printing auto generated struct in the console, we can add copy to clipboard functionality so that users can generate the struct and paste it where ever they want without copying it manually.

**Comment by Vhndaree** [comment]
@samit22 If you think this could add some value, I am up for the PR.

**Comment by samit22** [comment]
That would be great,@Vhndaree go ahead. 💯

**Comment by Vhndaree** [comment]
@samit22  I have added a PR please check.

**Comment by samit22** [comment]
Solved by #5
